import { v4 as uuidv4 } from "uuid";

export const playlist = [
  {
    id: uuidv4(),
    title: "Dawn Chorus",
    artists: ["Thom Yorke"],
    album: "Anima",
    url: "https://open.spotify.com/track/3bXH9y487cnLfA6VWXefaB?si=c1c3c770b19d4d1f",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "I Know",
    artists: ["Fiona Apple"],
    album: "When the Pawn",
    url: "https://open.spotify.com/track/0uhYgQQ6WX9rCONnum7Fmw?si=2965ddeb335b42f7",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "María la Curandera",
    artists: ["Natalia Lafourcade"],
    album: "De Todas Las Flores",
    url: "https://open.spotify.com/track/1xNi99xP8ioHUGXB5HrpNb?si=e6af04de72984f99",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Let's Get It On",
    artists: ["Marvin Gaye"],
    album: "Let's Get It On",
    url: "https://open.spotify.com/track/0jHkgTtTaqg5LNCiYDQPUB?si=c0700b02cb144122",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Real Love Baby",
    artists: ["Father John Misty"],
    album: "Pure Comedy",
    url: "https://open.spotify.com/track/0Z57YWES04xGh3AImDz6Qr?si=1a6379812aca40b2",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "U-Love",
    artists: ["J Dilla"],
    album: "Donuts",
    url: "https://open.spotify.com/track/4S6Bo2c9FzVaq0vdqqLqgU?si=d1c8183c89ee480c",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Mas O Menos Ante",
    artists: ["Silvana Estrada"],
    album: "Marchita",
    url: "https://open.spotify.com/track/1NttZF0RMI3NnWRVIcM81u?si=2d6c7035959a4123",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Rigamortus",
    artists: ["Kendrick Lamar"],
    album: "Section.80",
    url: "https://open.spotify.com/track/2lD6AoA8qf2t4Dkf2TcmNK?si=c1ed30d042f0454f",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Meat Grinder",
    artists: ["MF Doom", "MadLib"],
    album: "Madvillainy",
    url: "https://open.spotify.com/track/4WM1hvYr2NC6bQnQXcj3sH?si=59a10e6ba1634dd3",
    played: 0,
  },
  {
    id: uuidv4(),
    title: "Everyday",
    artists: ["Weyes Blood"],
    album: "Titanic Rising",
    url: "https://open.spotify.com/track/2VYqgye3Wf9ySE4qYM3iJn?si=e8b25c7fb5c24909",
    played: 0,
  },
];
